### ISSUE TITLE
helm repo add starlingx failure during config controller

### ISSUE THREAD

**Issue by ccollicutt** [ccollicutt/starlingx-workshop#12]
```
2019-04-25T19:41:25.077 ^[[0;36mDebug: 2019-04-25 19:41:25 +0000 Exec[generate helm repo index on target](provider=posix): Executing 'helm repo index /www/pages/helm_charts'^[[0m
2019-04-25T19:41:25.079 ^[[0;36mDebug: 2019-04-25 19:41:25 +0000 Executing with uid=www gid=www: 'helm repo index /www/pages/helm_charts'^[[0m
2019-04-25T19:41:25.099 ^[[mNotice: 2019-04-25 19:41:25 +0000 /Stage[main]/Platform::Helm/Exec[generate helm repo index on target]/returns: executed successfully^[[0m
2019-04-25T19:41:25.101 ^[[0;36mDebug: 2019-04-25 19:41:25 +0000 /Stage[main]/Platform::Helm/Exec[generate helm repo index on target]: The container Class[Platform::Helm] will propagate my refresh event^[[0m
2019-04-25T19:41:25.103 ^[[0;36mDebug: 2019-04-25 19:41:25 +0000 Exec[add local starlingx helm repo](provider=posix): Executing 'helm repo add starlingx http://127.0.0.1:8080/helm_charts'^[[0m
2019-04-25T19:41:25.107 ^[[0;36mDebug: 2019-04-25 19:41:25 +0000 Executing with uid=wrsroot gid=wrs: 'helm repo add starlingx http://127.0.0.1:8080/helm_charts'^[[0m
2019-04-25T19:41:25.138 ^[[mNotice: 2019-04-25 19:41:25 +0000 /Stage[main]/Platform::Helm/Exec[add local starlingx helm repo]/returns: Error: Looks like "http://127.0.0.1:8080/helm_charts" is not a valid chart repository or cannot be reached: Get http://127.0.0.1:8080/helm_charts/index.yaml: dial tcp 127.0.0.1:8080: connect: connection refused^[[0m
2019-04-25T19:41:25.140 ^[[1;31mError: 2019-04-25 19:41:25 +0000 helm repo add starlingx http://127.0.0.1:8080/helm_charts returned 1 instead of one of [0]
2019-04-25T19:41:25.142 /usr/share/ruby/vendor_ruby/puppet/util/errors.rb:106:in `fail'
2019-04-25T19:41:25.144 /usr/share/ruby/vendor_ruby/puppet/type/exec.rb:160:in `sync'
2019-04-25T19:41:25.146 /usr/share/ruby/vendor_ruby/puppet/transaction/resource_harness.rb:236:in `sync'
2019-04-25T19:41:25.148 /usr/share/ruby/vendor_ruby/puppet/transaction/resource_harness.rb:134:in `sync_if_needed'
2019-04-25T19:41:25.150 /usr/share/ruby/vendor_ruby/puppet/transaction/resource_harness.rb:88:in `block in perform_changes'
2019-04-25T19:41:25.152 /usr/share/ruby/vendor_ruby/puppet/transaction/resource_harness.rb:87:in `each'
2019-04-25T19:41:25.153 /usr/share/ruby/vendor_ruby/puppet/transaction/resource_harness.rb:87:in `perform_changes'
2019-04-25T19:41:25.155 /usr/share/ruby/vendor_ruby/puppet/transaction/resource_harness.rb:21:in `evaluate'
2019-04-25T19:41:25.157 /usr/share/ruby/vendor_ruby/puppet/transaction.rb:230:in `apply'
2019-04-25T19:41:25.159 /usr/share/ruby/vendor_ruby/puppet/transaction.rb:246:in `eval_resource'
2019-04-25T19:41:25.164 /usr/share/ruby/vendor_ruby/puppet/transaction.rb:163:in `call'
2019-04-25T19:41:25.166 /usr/share/ruby/vendor_ruby/puppet/transaction.rb:163:in `block (2 levels) in evaluate'
2019-04-25T19:41:25.168 /usr/share/ruby/vendor_ruby/puppet/util.rb:386:in `block in thinmark'
2019-04-25T19:41:25.170 /usr/share/ruby/benchmark.rb:296:in `realtime'
2019-04-25T19:41:25.172 /usr/share/ruby/vendor_ruby/puppet/util.rb:385:in `thinmark'

```

**Comment by ccollicutt** [comment]
During the workshop probably 1/10 recieved this error. Many reset the workshop and ran it again, only to get the same error. Moving to another node seemed to help this,though that doesn't make much sense as this seems to be some kind of timing error.
